### ISSUE TITLE
Sublime Text Port

### ISSUE THREAD

**Issue by wldcordeiro** [nikhilkalige/git-log#10]
I'm not sure how possible it is, but if that's doable it'd be awesome!

**Comment by D-side** [comment]
AFAIK, Sublime's UI can only display text of different flavors (code, menus, searchable lists). So the best possible result wouldn't be much prettier than `git log --graph` in your preferred terminal. You could do about the same with SublimeREPL (Shell) by issuing this same command. Here's a fragment of me trying that out on `base16-builder` repo:

![](http://i.imgur.com/cE6EkzT.png)

Can't exactly call it pretty, it loses all the coloring from the terminal output.  
Here's what it's intended to look like:

![](http://i.imgur.com/Cf3nqLo.png)

In that sense, Atom's high resource comsumption (it **is** higher than that of Sublime's) is justified by the ability to display everything browsers can, including graphs like we have here.

Of course, dropping the graphing part makes this totally possible.
