### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by halleycarleton** [NikhilKalige/git-log#26]
I just installed this package and it doesn't show up in the packages drop-down menu. So how do I view the log graph?

I'm not sure if I'm experiencing a bug or just missing something.

Perhaps some better documentation is in order.

**Comment by halleycarleton** [comment]
Answer:

Command Pallete: "Git Log:Show"

It is not available in the packages menu.

**Comment by guillim** [comment]
> It is not available in the packages menu.  

Unfortunate, that would be cool for those like me who go by instinct in the menu first :)
