### ISSUE TITLE
Fonts not rendering properly

### ISSUE THREAD

**Issue by komputerwiz** [NikhilKalige/git-log#42]
Font size is rendering too large (19.2px). Inspector shows that font size setting is not being retrieved correctly from configuration, hence user modifications to `editor` and `git-log` package configuration values are not reflected in the Git Log view.

![atom-git-log-font-size](https://cloud.githubusercontent.com/assets/369238/6132442/3782e59c-b118-11e4-9d45-ebbdc4680ce5.png)

**Comment by NikhilKalige** [comment]
Merged #24 Thank you for the PR
